### ISSUE TITLE
'Unauthorized Realtime user (session)'

### ISSUE THREAD

**Issue by ravirupapara** [mikeatlas/realtime-server#3]
How can i rid from this issue ?

**Comment by mikeatlas** [comment]
Can you please specify more information? Sample code? What you've tried and what you haven't tried? It go would go a long way to helping me help you out... Read this please: http://stackoverflow.com/help/how-to-ask as well as this: http://www.catb.org/~esr/faqs/smart-questions.html

Well, anyways: 

Do you have Rails set up to store the `rtSession-{userId}:{sessionId}` key/value pair in Redis? This is the mechanism for sharing authorization between Rails and the Socket.io connection. 

Further, refer to the [documentation](http://mikeatlas.github.io/realtime-rails/) regarding how to specify the Rails user id your the application controller. You'll need to set it to whatever the user ID is, not the sample value "42" in the example.

Lastly, you can watch from your browser the XHR traffic connecting to your node.js realtime server, you should see a connection to the realtime server with GET parameters [which get used](https://github.com/mikeatlas/realtime-server/blob/master/environment.js#L74) to confirm round-trip authorization.

**Comment by ravirupapara** [comment]
```
export default class Realtime {

  constructor(options) {
    this.options = options;
    this.socketUrl = options.socketUrl || this.defaultSocketUrl;
    this.connect();
  }

  get defaultSocketUrl() {
    return [[this.defaultUrl, this.defaultPort].join(':'), this.defaultParam].join('?');
  }

  get defaultUrl() {
    return 'http://127.0.0.1';
  }

  get defaultPort() {
    return '5001';
  }

  get defaultParam() {
    return '_rtUserId=42&_rtToken=610f36bf16d89c12f400414ce1fd8ab3';
  }

  get options() {
    return this.options;
  }

  connect() {
    var socket = io.connect(this.socketUrl);
    socket.on('connect', function() {
      EventLogger.log('connected');
    });
    socket.on('realtime_msg', function(message) {
      EventLogger.log(message);
    });
  }
}
```

This is work after specifying static param like this.

If i don't specify param userid and token it won't be work.

And yes I also have Redis to store rtSession.

Is there any solution?

**Comment by mikeatlas** [comment]
Is this an ECMAScript port of the `realtime-server`? Interesting. The user id and session token are passed on Socket.io's `connect` from the web front end; as I said earlier, check your browser's XHR network traffic and make sure you're passing along those as GET parameters when initializing your connection. 

See https://github.com/mikeatlas/realtime-rails/blob/master/app/views/realtime/realtime_support.html.erb#L16 for where this parameter is sent to the realtime-server.

I've deliberately written the gem to be user-centric around realtime updates and avoided complications about channels; that's something you can implement yourself or leverage in Socket.io, or as a complete solution such as using [Faye](http://faye.jcoglan.com/), which you can swap out in lieu of this server... or fork and customize it to your business needs. Having "default" parameters in your realtime backend here sure would _work_ but you'd have no notion of user or session authentication. I'd advise against it unless that's your intention.

**Comment by mikeatlas** [comment]
So, it does seem that you are well off to forking this project to your own needs. If you find a bug or error in the documentation or samples, please re-open and let me know.
