### ISSUE TITLE
heroku websockets

### ISSUE THREAD

**Issue by fabianrios** [mikeatlas/realtime-server#4]
"If you host this Node.js server on Heroku, you'll need to enable websockets for this application."
can you please explain this further.

**Comment by mikeatlas** [comment]
My gem/sample server is a bit older than the latest support for websockets on Heroku:

"WebSocket support is available everywhere, except SSL endpoint traffic for endpoints created before July 7th, 2014." 

https://devcenter.heroku.com/articles/websockets

In the past, you needed to issue a Heroku CLI command to enable websockets support on your app endpoint.
