### ISSUE TITLE
Hi can you please explain further the heroku websockets

### ISSUE THREAD

**Issue by fabianrios** [mikeatlas/realtime-server#5]

**Comment by mikeatlas** [comment]
At the time of writing (mid 2014), Heroku did not officially support websockets and you had to turn on experimental support for a heroku-hosted application to leverage websockets. Presently (as of at least your last #4 anyways), they are now fully supported and thus you don't need to enable them; support for them is available across all Cedar-14 stack applications as far as I'm aware.

https://blog.heroku.com/archives/2013/10/8/websockets-public-beta (Applicable during the time of writing this sample repo)
https://blog.heroku.com/archives/2014/7/7/websockets_now_ga (WebSocket support went GA shortly after I published my sample Node.js server, this repository)
https://devcenter.heroku.com/articles/websockets (main article on websockets on heroku today, 2015)

My gem and sample servers use Socket.io, which doesn't require websockets actually, and [could gracefully degrade](http://stackoverflow.com/questions/10112178/differences-between-socket-io-and-websockets) if necessary. Although, WebSocket technology has been around now long enough to be [widely implemented in most browsers](http://caniuse.com/#feat=websockets). 

Further information:
https://devcenter.heroku.com/articles/websocket-security
https://en.wikipedia.org/wiki/WebSocket
